### ISSUE TITLE
Access Violation in Lobby

### ISSUE THREAD

**Issue by Scrxtchy** [RokasKil/TitleEdit#6]
Been getting this crash often enough for a while, thought it would be best to start tracking it now

<details><summary>dalamud_appcrash</summary>

```
Unhandled native exception occurred at ffxiv_dx11.exe+6BCCD0	(Client::LayoutEngine::LayoutManager.SetActiveFestivals)
Code: C0000005
Dump at: [...]\AppData\Roaming\XIVLauncher\dalamud_appcrash_20241219_185447_626_74236.dmp
System Time: 2024-12-19 07:54:54.5966495

   at TitleEdit.PluginServices.LayoutService.LayoutWorldInitManagerDetour(IntPtr p1, UInt32 p2, IntPtr p3, UInt32 p4, UInt32 p5, IntPtr p6, UInt32 p7)

   at TitleEdit.PluginServices.Lobby.LobbyService.CreateSceneDetour(String territoryPath, UInt32 territoryId, IntPtr p3, UInt32 layerFilterKey, IntPtr p5, Int32 p6, UInt32 contentFinderConditionId)

   at TitleEdit.PluginServices.Lobby.LobbyService.UpdateLobbyUiStageDetour(AgentLobby* agentLobby)

   at Dalamud.Game.Framework.HandleFrameworkUpdate(Framework* thisPtr)



Exception Info #0
Address: C0000005
Flags: 0
Address: 7FF71573CCD0
Parameters: 0, 0
Call Stack
{
  [0]	ffxiv_dx11.exe+6BCCD0	(Client::LayoutEngine::LayoutManager.SetActiveFestivals)
  [1]	ffxiv_dx11.exe+6BCCD0	(Client::LayoutEngine::LayoutManager.SetActiveFestivals)
  [2]	ffxiv_dx11.exe+6B082C	(sub_1406B06C0+0x16C)
  [3]	7FF7ED686C0F
}

Registers
{
  RAX:	1BC01
  RBX:	1E2DDD6A3F0 [ffxiv_dx11.exe+1F69DE0	(vtbl_Client::LayoutEngine::Streaming::StreamingManager)]
  RCX:	1A11F1FC920 [ffxiv_dx11.exe+1F69E00	(vtbl_Client::LayoutEngine::LayoutManager)]
  RDX:	0
  R8:	ffxiv_dx11.exe+0	(_ImageBase)
  R9:	1E1E74CBD00 [1E1E76F9200]
  R10:	8000
  R11:	16DCB2DDF0 [1A145C93810]
  R12:	2
  R13:	B1
  R14:	16DCB2E3A0 [65732F7669786666]
  R15:	1A145C93810
  RSI:	1A11F1FC920 [ffxiv_dx11.exe+1F69E00	(vtbl_Client::LayoutEngine::LayoutManager)]
  RDI:	1E27962C440 [ffxiv_dx11.exe+1F69DB8	(vtbl_Client::LayoutEngine::LayoutWorld)]
  RBP:	D617D0BA
  RSP:	16DCB2DF78 [ffxiv_dx11.exe+6B082C	(sub_1406B06C0+0x16C)]
  RIP:	ffxiv_dx11.exe+6BCCD0	(Client::LayoutEngine::LayoutManager.SetActiveFestivals)
}

Stack
{
  [RSP+0]	ffxiv_dx11.exe+6B082C	(sub_1406B06C0+0x16C)
  [RSP+8]	D617D0BA
  [RSP+10]	1A11F1FC920 [ffxiv_dx11.exe+1F69E00	(vtbl_Client::LayoutEngine::LayoutManager)]
  [RSP+18]	D617D0BA
  [RSP+20]	1E27962C400
  [RSP+28]	1E31DF76E30 [1E311379760]
  [RSP+30]	3FF
  [RSP+38]	1A143420150 [1E302397A30]
  [RSP+40]	C000000
  [RSP+48]	1A14344793C [400140001711549]
  [RSP+50]	12A
  [RSP+58]	1E2D617D0BA
  [RSP+60]	1E2CF2F00A0 [FF3B61E56D3F817A]
  [RSP+68]	76697866662F6762
  [RSP+70]	2F31735F6165732F
  [RSP+78]	697431732F6E7774
}
```
</details> 

if it helps, I can throw the dump somewhere.
I haven't spent time to trace this on a debugger since it's inconsistent, and a quick gander at the code it wasn't immediately clear how the exception leads to the call stack

**Comment by RokasKil** [comment]
Hi, turn on debug logging via /xllog and next time you crash send me a full .tspack, can send it on discord at speedas or in dalamud's TitleEdit channel

**Comment by Scrxtchy** [comment]
[crash-20241223194911.tspack.zip](https://github.com/user-attachments/files/18227507/crash-20241223194911.tspack.zip)

Took a while but here it is

**Comment by RokasKil** [comment]
The issue is caused by HaselTweak's Enhanced Login/Logout's Preload territory when queued feature, you manage to enter the queue and preload the territory before TitleEdit loads it, so the game sees that the territory is already preloaded and tries to use that, but the lobby system was not designed with preloads in mind and passes nulls that do not get checked leading to the access violation.

I'll push out an update that unloads the preloaded territories when changing scenes which should fix this, in the mean time you can disable that feature in HaselTweaks
